#undef Tnum
#undef Pnum
#undef CPnum
#undef Tsize
#undef Psize
#undef CPsize
#undef MATH_COS
#undef MATH_SIN
#undef MATH_TAN
#undef MATH_ACOS
#undef MATH_ASIN
#undef MATH_ATAN
#undef MATH_ATAN2
#undef MATH_ABS
#undef MATH_PI
#undef MATH_PI2
#undef MATH_PI4
#undef MATH_SQRT
#undef MATH_COSH
#undef MATH_SINH
#undef MATH_TANH
#undef MATH_DEG2RAD
#undef _0
#undef _1
#undef _2
#undef MIN_L2SUM
#undef NUMFORMATS
#undef WRITENUMF
