#define	ESUCCESS		0
#define	ERR_SUCCESS		ESUCCESS
#define	ERR_MATRIX		0x4000
#define	ERR_MATRIX_ILLFORMED	ERR_MATRIX
#define	ERR_MATRIX_SINGULAR	(ERR_MATRIX + 1)
#define	ERR_MATRIX_SIZEMISMATCH	(ERR_MATRIX + 2)

